### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by r-cemper** [intersystems-ru/fhir-terminology-service#2]
in several places HS has changed!

HSLIB>do ##class(HS.HC.Util.Installer).InstallFoundation("terminology")

DO ##CLASS(HS.HC.Util.Installer).InstallFoundation("terminology")
^
**<METHOD DOES NOT EXIST**> *InstallFoundation,HS.HC.Util.Installer

$ZV:
IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.2 (Build 227U) Mon Jul 31 2023 18:04:28 EDT **[Health:5.1.3]**

**Comment by dmitry-zasypkin** [comment]
Fixed. Thank you, Robert.
